sudo: required
services:
  - docker

before_install:
  - docker build -t filipemonteiro/simpleweb -f Dockerfile.dev .

script:
  - docker run filipemonteiro/simpleweb npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "simpleweb"
  env: "Simpleweb-env"
  bucket_name: "elasticbeanstalk-us-east-2-230705462750"
  bucket_path: "simpleweb"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
